### ISSUE TITLE
AVA to Jest codemod

### ISSUE THREAD

**Issue by skovhus** [skovhus/jest-codemods#6]
## TODO
Unsupported, make warning
- [x] chaining test.serial.only for hooks
- [x] test.todo(title)
- [x] test.failing([title], implementation)
- [x] t.plan

Remap
- [x] test.serial([title], implementation) *remove serial (all tests are serial)*
- [x] test.cb([title], implementation) *remove cb (all tests are callback style by default)*
- [x] test.only([title], implementation) *fit*
- [x] test.skip([title], implementation) *xit*
- [x] test.before([title], implementation)
- [x] test.after([title], implementation)
- [x] test.beforeEach([title], implementation)
- [x] test.afterEach([title], implementation)

Investigate
- [ ] Test macros

Finalize
- [x] integrate with CLI
- [x] README update
- [x] `it` or `test`
- [ ] do we want nice formatting like of equals like https://github.com/mikenikles/jscodeshift-ava-to-jest/blob/master/jest-tests/deep-equal.test.js#L3
- [ ] do we want to support keeping formatting? See example below

```javascript
-        t.deepEqual(
-            embed,
-            omit(validatedEmbeds[index], 'validation'),
-            'does not modify the rest of embed ' + index
-        );
+        expect(embed).toEqual(omit(validatedEmbeds[index], 'validation'));
```
